### ISSUE TITLE
ユーザネームの変更: ottatiyarou => ottati

### ISSUE THREAD

**Issue by yat1ma30** [y-takey/tetris#1]
お世話になります
usernameの変更に伴いURLも変更されました
old: https://gist.github.com/ottatiyarou/6560440
new: https://gist.github.com/ottati/6560440

٩(๑❛ᴗ❛๑)۶

**Comment by y-takey** [comment]
@ottati ご連絡ありがとうございます！READMEのURLを変更いたしました。

とても今更ではあるのですが。。。コードレシピのサイトでは大変勉強させていただきました。ありがとうございます。

**Comment by yat1ma30** [comment]
@y-takey ありがとうございます！少しでも役に立てたなら嬉しいです！
